steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - slack-build-notification
  - --region=us-central1
  - --runtime=nodejs14
  - --set-env-vars=SLACK_WEBHOOK_URL=$_SLACK_WEBHOOK_URL
  - --entry-point=subscribe
  - --trigger-topic=cloud-builds
  - --source=.